Improved docker support Updated README for docker Cleaned up run and build bash scripts

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,139 +2,90 @@
 
 SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)
 
-BUILD_MS=0
+CLEAN=0
 BUILD_GS=0
-CLEAN_MS=0
-CLEAN_GS=0
 SKIPTEST=""
 
 GS_SRC=$SCRIPT_DIR/Server
-MS_SRC=$SCRIPT_DIR/Management-Server
 
-CLEANOPT=""
 _JAR_DIR="$SCRIPT_DIR/builddir"
 
 help()
 {
-    echo "Usage: $0 [-h] <-m | -g> [-c <m|g>] [-o <path>]";
+    echo "Usage: $0 [-h] [-q] <-g|-c> [-o <path>]";
     echo "  -h: Display this message.";
-    echo "  -m: Build the management server.";
     echo "  -g: Build the game server.";
-    echo "  -c: Clean: m: management, g: gameserver. "
-    echo "      Can specify both. Need at least one if present.";
-    echo "  -o: Specify jar-file directory."
+    echo "  -c: Clean previous build.";
+    echo "  -o: Specify jar-file directory.";
     echo "  -q: Quick build - will skip tests.";
 }
 
 error()
 {
-    echo $1;
-    exit -1;
-}
-
-clean_ms()
-{
-    cd $MS_SRC
-
-    if [[ "$CLEANOPT" == *"m"* ]]; then
-	echo "Cleaning the management server."
-        sh mvnw clean || error "Failed to clean the MS."
-    fi
+    echo "$1";
+    exit 1;
 }
 
 clean_gs()
 {
-    cd $GS_SRC;
-    if [[ "$CLEANOPT" == *"g"* ]]; then
+    cd $GS_SRC || error "Could not change dir to game server directory."
 	echo "Cleaning the game server."
-        sh mvnw clean || error "Failed to clean the game server. Giving up."
-    fi
-}
-
-build_ms()
-{
-    cd $MS_SRC
-
-    sh mvnw package $SKIPTEST || \
-	error "Failed to build the management server. Giving up";
+    sh mvnw clean || error "Failed to clean the game server. Giving up."
 }
 
 build_gs()
 {
-    cd $GS_SRC;
+    cd "$GS_SRC" || error "ERROR: Could not chdir to server src. Abort."
 
     sh mvnw package $SKIPTEST || \
 	error "Failed to build the game server. Giving up."
 }
 
-while getopts "hqmgc:o:d" arg; do
+while getopts "hqgc:o:d" arg; do
     case $arg in
         h)
             help
             exit 0
             ;;
-        m)
-            BUILD_MS=1
-            ;;
         g)
             BUILD_GS=1
             ;;
         c)
-            CLEANOPT=${OPTARG}
+            CLEAN=1
             ;;
         o)
             _JAR_DIR=${OPTARG}
             ;;
         d)
-            echo "BUILD_MS=$BUILD_MS"
-            echo "BUILD_GS=$BUILD_GS"
-            echo "CLEANOPT=$CLEANOPT"
             echo "_JAR_DIR=$_JAR_DIR"
             ;;
         q)
             SKIPTEST="-DskipTests"
             ;;
+        *)
+            error "Argument -$arg is not a known or valid argument."
+            ;;
     esac
 done
 
-if [[ $CLEANOPT != "m" ]]       \
-    && [[ $CLEANOPT != "g" ]]   \
-    && [[ $CLEANOPT != "mg" ]]  \
-    && [[ $CLEANOPT != "" ]]; 
-then
-    error "Invalid cleaning option '$CLEANOPT'. Valid options are 'm', 'g', 'mg' or none."
+if [ $BUILD_GS -eq 0 ] && [ $CLEAN -eq 0 ]; then
+    error "Need to either build or clean at least. See -h for details."
 fi
 
-if [ $BUILD_MS -eq 0 ] && [ $BUILD_GS -eq 0 ] && [[ $CLEANOPT == "" ]]; then
-    error "Need to build or clean at least one of the modules. See -h for details."
-fi
+# Inside func is cd so mgmt prob fails if no condition
+(( CLEAN )) && clean_gs
 
-# Conditionals inside the functions.
-clean_gs
-clean_ms
 # -----------
 
-if [ -d $_JAR_DIR ]; then
-    rm -r $_JAR_DIR
+if [ -d "$_JAR_DIR" ]; then
+    rm -r "$_JAR_DIR"
 fi
 
-if [ $BUILD_MS -ne 1 ] && [ $BUILD_GS -ne 1 ]; then
-    echo "No build options specified. Stop."
-    exit 0
-fi
-
-mkdir -p $_JAR_DIR || error "Failed to create build directory.";
-
-if [ $BUILD_MS -eq 1 ]; then
-    build_ms
-
-    # Will never execute if build_ms fails because it quits upon failure.
-    mv -v $MS_SRC/target/*-with-dependencies.jar $_JAR_DIR/ms.jar
-fi
+mkdir -p "$_JAR_DIR" || error "Failed to create build directory.";
 
 if [ $BUILD_GS -eq 1 ]; then
     build_gs
 
     # Will never execute if build_gs fails because it quits upon failure.
-    mv -v $GS_SRC/target/*-with-dependencies.jar $_JAR_DIR/server.jar
+    mv -v "$GS_SRC"/target/*-with-dependencies.jar "$_JAR_DIR"/server.jar
 fi
diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,15 +3,11 @@ SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)
 LOG_DIR=$SCRIPT_DIR/logs
 BUILD_DIR=$SCRIPT_DIR/builddir
 GS_SRC=$SCRIPT_DIR/Server
-MS_SRC=$SCRIPT_DIR/Management-Server
 
 FORCE_REBUILD=0
 REFRESH_BUILD=1
 
-GAMESERVER_ONLY=1
-
 GS_EXEC="cd $GS_SRC && java -Dnashorn.args=--no-deprecation-warning -jar $BUILD_DIR/server.jar"
-MS_EXEC="cd $MS_SRC && java -Dnashorn.args=--no-deprecation-warning -jar $BUILD_DIR/ms.jar"
 
 # 0: parallel
 # 1: fancy tmux
@@ -20,13 +16,12 @@ RUN_MODE=0
 
 help()
 {
-    echo "Usage: $0 [-h] [-q] [-r] [-t] [-x] [-g] [-e <filename>] [-o <filename>]"
+    echo "Usage: $0 [-h] [-q] [-r] [-t] [-x] [-e <filename>] [-o <filename>]"
     echo "  -h: Display this message."
     echo "  -q: Don't perform the incremental build."
     echo "  -r: Force clean rebuild."
     echo "  -t: Only run tests, not the JARs."
     echo "  -x: Run in a fancy tmux session."
-    echo "  -g: Build + run only the game server (no management server)."
     echo "  -e: Write STDERR to 'logs/filename' as well as the terminal.";
     echo "  -o: Write STDOUT to 'logs/filename' as well as the terminal."
 }
@@ -39,31 +34,17 @@ error()
 
 rebuild_project()
 {
-    if [ $GAMESERVER_ONLY ]; then
-      $SCRIPT_DIR/build -qgcg
-    else
-      $SCRIPT_DIR/build -qmgcmg
-    fi
+    "$SCRIPT_DIR/build" -qgc
 }
 
 refresh_project()
 {
-    if [ $GAMESERVER_ONLY ]; then
-      $SCRIPT_DIR/build -qg
-    else
-      $SCRIPT_DIR/build -qmg
-    fi
+    "$SCRIPT_DIR/build" -qg
 }
 
 verify_binaries_exist()
 {
-    if ! [ $GAMESERVER_ONLY ]; then
-      if [ ! -f $SCRIPT_DIR/builddir/ms.jar ]; then
-          error "Management server binary does not exist.";
-      fi
-    fi
-
-    if [ ! -f $SCRIPT_DIR/build/server.jar ]; then
+    if [ ! -f "$SCRIPT_DIR/build/server.jar" ]; then
         error "Game server binary does not exist.";
     fi
 }
@@ -76,11 +57,7 @@ run_server_parallel()
 
     echo "Running in parallel. All logs redirected to proper files."
 
-    if [ $GAMESERVER_ONLY ]; then
-        sh -c "$GS_EXEC" & wait
-    else
-        sh -c "$MS_EXEC > $LOG_DIR/ms_stdout.log 2> $LOG_DIR/ms_stderr.log & $GS_EXEC" & wait
-    fi
+    sh -c "$GS_EXEC" & wait
 }
 
 run_server_tmux()
@@ -89,21 +66,16 @@ run_server_tmux()
         error "tmux is not installed. Install tmux or don't use this option."
     fi
 
-    if [ $GAMESERVER_ONLY ]; then
-        tmux new-session "$GS_EXEC"
-    else
-        tmux new-session "$MS_EXEC" \; \
-            split-window -h "$GS_EXEC"
-    fi
+    tmux new-session "$GS_EXEC"
 }
 
 run_server_tests()
 {
-    cd "$GS_SRC" || error "Could not change to GameServer source directory."
+    cd "$GS_SRC" || error "Could not change to game server source directory."
     sh mvnw test
 }
 
-while getopts ":ghqrtxe:o:" arg; do
+while getopts ":hqrtxe:o:" arg; do
     case $arg in
         h)
             help
@@ -126,9 +98,6 @@ while getopts ":ghqrtxe:o:" arg; do
             ;;
         x)
             RUN_MODE=1
-            ;;
-        g)
-            GAMESERVER_ONLY=0
             ;;
         *)
             error "Argument -$arg is not a known or valid argument."
