Fixed any shellcheck issues in the run and build scripts
https://www.shellcheck.net/ is a shell script analysis tool that warns
for common pitfalls and mistakes in shell scripts.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,11 +1,9 @@
 #!/bin/bash
 
-SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)
+SCRIPT_DIR=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit; pwd -P)
 
 BUILD_MS=0
 BUILD_GS=0
-CLEAN_MS=0
-CLEAN_GS=0
 SKIPTEST=""
 
 GS_SRC=$SCRIPT_DIR/Server
@@ -28,13 +26,13 @@ help()
 
 error()
 {
-    echo $1;
-    exit -1;
+    echo "$1";
+    exit 1;
 }
 
 clean_ms()
 {
-    cd $MS_SRC
+    cd "$MS_SRC" || exit
 
     if [[ "$CLEANOPT" == *"m"* ]]; then
 	echo "Cleaning the management server."
@@ -44,7 +42,7 @@ clean_ms()
 
 clean_gs()
 {
-    cd $GS_SRC;
+    cd "$GS_SRC" || exit
     if [[ "$CLEANOPT" == *"g"* ]]; then
 	echo "Cleaning the game server."
         sh mvnw clean || error "Failed to clean the game server. Giving up."
@@ -53,26 +51,32 @@ clean_gs()
 
 build_ms()
 {
-    cd $MS_SRC
+    cd "$MS_SRC" || exit
 
-    sh mvnw package $SKIPTEST || \
-	error "Failed to build the management server. Giving up";
+    if [ -z "$SKIPTEST" ]; then
+        sh mvnw package || \
+            error "Failed to build the management server. Giving up";
+    else
+        sh mvnw package "$SKIPTEST" || \
+            error "Failed to build the management server. Giving up";
+    fi
 }
 
 build_gs()
 {
-    cd $GS_SRC;
+    cd "$GS_SRC" || exit
 
-    sh mvnw package $SKIPTEST || \
-	error "Failed to build the game server. Giving up."
+    if [ -z "$SKIPTEST" ]; then
+        sh mvnw package || \
+            error "Failed to build the game server. Giving up."
+    else
+        sh mvnw package "$SKIPTEST" || \
+            error "Failed to build the game server. Giving up."
+
 }
 
 while getopts "hqmgc:o:d" arg; do
     case $arg in
-        h)
-            help
-            exit 0
-            ;;
         m)
             BUILD_MS=1
             ;;
@@ -94,6 +98,10 @@ while getopts "hqmgc:o:d" arg; do
         q)
             SKIPTEST="-DskipTests"
             ;;
+		h|*)
+			help
+			exit 0
+			;;
     esac
 done
 
@@ -114,8 +122,8 @@ clean_gs
 clean_ms
 # -----------
 
-if [ -d $_JAR_DIR ]; then
-    rm -r $_JAR_DIR
+if [ -d "$_JAR_DIR" ]; then
+    rm -r "$_JAR_DIR"
 fi
 
 if [ $BUILD_MS -ne 1 ] && [ $BUILD_GS -ne 1 ]; then
@@ -123,18 +131,18 @@ if [ $BUILD_MS -ne 1 ] && [ $BUILD_GS -ne 1 ]; then
     exit 0
 fi
 
-mkdir -p $_JAR_DIR || error "Failed to create build directory.";
+mkdir -p "$_JAR_DIR" || error "Failed to create build directory.";
 
 if [ $BUILD_MS -eq 1 ]; then
     build_ms
 
     # Will never execute if build_ms fails because it quits upon failure.
-    mv -v $MS_SRC/target/*-with-dependencies.jar $_JAR_DIR/ms.jar
+    mv -v "$MS_SRC"/target/*-with-dependencies.jar "$_JAR_DIR"/ms.jar
 fi
 
 if [ $BUILD_GS -eq 1 ]; then
     build_gs
 
     # Will never execute if build_gs fails because it quits upon failure.
-    mv -v $GS_SRC/target/*-with-dependencies.jar $_JAR_DIR/server.jar
+    mv -v "$GS_SRC"/target/*-with-dependencies.jar "$_JAR_DIR"/server.jar
 fi
